[core/cli]
task_name = core/task/supervised
device = cpu
from_ckpt_dir = ./cache
cache_dir = ./cache
test_file = ./test.tsv

# model
[core/model/vllm/generation/qwen3]
pretrained_name = qwen3-4b-thinking
# hf_name_or_folder = /path/to/local/model
max_gen_seq_length = 512
tensor_parallel_size = 1
pipeline_parallel_size = 1
gpu_memory_utilization = 0.90
# max_model_len = 12800
max_num_seqs = 256
enable_prefix_caching = True
dtype = auto
enforce_eager = False
# quantization = awq

# dataset
[core/dataset/ast]
names = ['prompt']

[core/dataset/ast/test]
data_files = ${core/cli:test_file}
preprocess_functions = [
    '''
    core/process/qwen/generation/inputs(
      core/process/qwen/chat_template(
        [
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                ],
            }
        ]
      )
    )
    '''
  ]

# process
[core/process/qwen]
pretrained_name = qwen3-4b-thinking
max_seq_length = 12800
max_gen_seq_length = 512

[core/writer/csv]
escapechar = \

# task
[core/task/supervised]
model = core/model/vllm/generation/qwen3
dataset = core/dataset/ast
output_header = ['prompt']
postprocess_fn = core/postprocess/qwen/detokenize
writer = core/writer/csv

from_ckpt_dir = ${core/cli:from_ckpt_dir}
output_path = ${core/cli:cache_dir}/output.txt
test_batch_size = 8
