[core/cli]
enabled_services = [
    "core/fastapi/interrogator/clip",
    "core/fastapi/llava/mistral_clip",
    "core/fastapi/qwen3",
    "core/fastapi/qwen3_vl",
    "core/fastapi/stable_flux/text2image",
    "core/fastapi/stable_flux/image2image",
    "core/fastapi/stable_flux/inpainting",
  ]
device = cpu

# pipeline
[core/fastapi/pipeline/interrogator/clip]
device = ${core/cli:device}

[core/fastapi/pipeline/llava/mistral_clip]
device = ${core/cli:device}

[core/fastapi/pipeline/qwen3]
device = ${core/cli:device}

[core/fastapi/pipeline/qwen3_vl]
device = ${core/cli:device}

[core/fastapi/pipeline/stable_flux/text2image]
device = ${core/cli:device}

[core/fastapi/pipeline/stable_flux/image2image]
device = ${core/cli:device}

[core/fastapi/pipeline/stable_flux/inpainting]
device = ${core/cli:device}
