[core/cli]
enabled_services = [
    "core/fastapi/gemma",
    "core/fastapi/gemma_vl",
    "core/fastapi/qwen3",
    "core/fastapi/qwen3_vl",
    "core/fastapi/flux2/text2image",
    "core/fastapi/flux2/editing",
    "core/fastapi/wan/text2video",
    "core/fastapi/wan/image2video",
    "core/fastapi/lucy/video_editing",
  ]
device = cpu
use_auth_token = True
health_check_timeout = 300

# pipeline
[core/fastapi/pipeline/gemma]
pretrained_name = gemma-4-12b
device = ${core/cli:device}
enable_cpu_offload = True

[core/fastapi/pipeline/gemma_vl]
pretrained_name = gemma-4-12b
device = ${core/cli:device}
enable_cpu_offload = True

[core/fastapi/pipeline/qwen3]
device = ${core/cli:device}

[core/fastapi/pipeline/qwen3_vl]
device = ${core/cli:device}

[core/fastapi/pipeline/flux2/text2image]
pretrained_name = flux2-klein-4b
use_auth_token = ${core/cli:use_auth_token}
device = ${core/cli:device}
max_sequence_length = 512
enable_cpu_offload = False

[core/fastapi/pipeline/flux2/editing]
pretrained_name = flux2-klein-4b
use_auth_token = ${core/cli:use_auth_token}
device = ${core/cli:device}
max_sequence_length = 512
enable_cpu_offload = False

[core/fastapi/pipeline/wan/text2video]
pretrained_name = wan-v2.2-ti2v-5b
device = ${core/cli:device}
num_infer_timesteps = 50
enable_cpu_offload = True

[core/fastapi/pipeline/wan/image2video]
pretrained_name = wan-v2.2-ti2v-5b
device = ${core/cli:device}
num_infer_timesteps = 50
enable_cpu_offload = True

[core/fastapi/pipeline/lucy/video_editing]
pretrained_name = lucy-edit-v1.1-dev
device = ${core/cli:device}
num_infer_timesteps = 50
expand_timesteps = True
enable_cpu_offload = True
