site_name: unitorch
site_description: A Comprehensive Modeling Framework Empowered by PyTorch
repo_name: fuliucansheng/unitorch
repo_url: https://github.com/fuliucansheng/unitorch
copyright: Copyright &copy; 2023 FULIUCANSHENG
docs_dir: wiki
site_dir: docs
site_url: https://fuliucansheng.github.io/unitorch

nav:
  - Home: index.md
  - Documentation:
    - Overview: overview.md
    - Installation: installation.md
    - References:
      - Models: models/index.md
      - Bart: models/bart.md
      - Beit: models/beit.md
      - Bert: models/bert.md
      - Blip: models/blip.md
      - Bloom: models/bloom.md
      - Clip: models/clip.md
      - Deberta: models/deberta.md
      - Diffusers: models/diffusers.md
      - Llama: models/llama.md
      - MBart: models/mbart.md
      - MT5: models/mt5.md
      - Peft: models/peft.md
      - Pegasus: models/pegasus.md
      - Roberta: models/roberta.md
      - Swin: models/swin.md
      - T5: models/t5.md
      - VisualBert: models/visualbert.md
      - ViT: models/vit.md
      - XLMRoberta: models/xlm_roberta.md
      - XPegasus: models/xpegasus.md
  - Commands:
    - Configuration: configuration.md
    - Examples:
      - Service: 
        - Zip Files: examples/service/zip_files.md
      - Classification:
        - Roberta: examples/classification/roberta.md
        - Swin: examples/classification/swin.md
        - Clip: examples/classification/clip.md
      - Caption: 
        - Blip: examples/caption/blip.md
      - Generation: 
        - Bart: examples/generation/bart.md
      # - Diffusion: 
      #  - ControlNet: examples/diffusion/controlnet.md
    - Task:
      - Supervised: cli/supervised.md
      - Deepspeed: cli/deepspeed.md
    - Dataset:
      - Ast: cli/ast.md
    - DataTypes: cli/datatypes.md
    - Processing:
      - Preprocess: cli/preprocess.md
      - Postprocess: cli/postprocess.md
    - Writer:
      - Csv: cli/csv.md
      - Jsonl: cli/jsonl.md
      - Parquet: cli/parquet.md
    - References:
      - Bart: cli/models/bart.md
      - Beit: cli/models/beit.md
      - Bert: cli/models/bert.md
      - Blip: cli/models/blip.md
      - Bloom: cli/models/bloom.md
      - Clip: cli/models/clip.md
      - Deberta: cli/models/deberta.md
      - Diffusers: cli/models/diffusers.md
      - Llama: cli/models/llama.md
      - MBart: cli/models/mbart.md
      - MT5: cli/models/mt5.md
      - Peft: cli/models/peft.md
      - Pegasus: cli/models/pegasus.md
      - Roberta: cli/models/roberta.md
      - Swin: cli/models/swin.md
      - T5: cli/models/t5.md
      - VisualBert: cli/models/visualbert.md
      - ViT: cli/models/vit.md
      - XLMRoberta: cli/models/xlm_roberta.md
      - XPegasus: cli/models/xpegasus.md
  # - Benchmarks: benchmarks/index.md
  # - Labs: labs/index.md

theme:
  name: material
  logo: icon.png
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.suggest
    - toc.follow
    - header.autohide
  icon:
    repo: fontawesome/brands/github
  favicon: icon.png
  palette:
    primary: white

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - codehilite
  #- callouts:
  #    strip_period: no
  - footnotes
  - md_in_html
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.tab:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "¤"

extra_css:
  - static/extra.css

plugins:
  - autorefs
  - search
  - markdown-exec
  - coverage
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            heading_level: 3
            show_root_heading: False
            show_root_toc_entry: False
            show_root_members_full_path: False
            merge_init_into_class: True
            show_docstring_examples: True
            show_bases: True
            signature_crossrefs: True
            show_signature: True
            show_signature_annotations: True
            separate_signature: True

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/fuliucansheng
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/fuliucansheng
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/unitorch/
  - icon: fontawesome/solid/paper-plane
    link: mailto:fuliucansheng@gmail.com
